### ISSUE TITLE
Blocked by uBlock Origin

### ISSUE THREAD

**Issue by Ziedelth** [vinceanalytics/vince#3]
Hello, I'm back
I think the script is blocked by ad blocker extensions.

I just tested on Firefox with uBlock Origin, and I have this message in the console:
```
Cross-Origin Request blocked: the "Same Origin" policy does not allow access to the remote resource located at https://analytics.shikkanime.fr/api/event. Reason: CORS request failed. Status code: (null).
```

I tested by deactivating the extension and no problem. I've also tried it with Brave and it's not blocked.

Is this normal?

**Comment by gernest** [comment]
This is a bug, CORS must be enabled on `/api/event` , I will investigate.

**Comment by gernest** [comment]
Can you help me show the headers returned from the blocked request ? Probably we are setting wrong headers.

**Comment by Ziedelth** [comment]
![image](https://github.com/vinceanalytics/vince/assets/45169338/60401624-c743-4095-8ab4-9b54a6f8d210)

**Comment by gernest** [comment]
Yes, thanks.

**Comment by gernest** [comment]
Are you running vince standalone or behind a reverse proxy?

**Comment by gernest** [comment]
You should  remove the comment on `#       Header always set Access-Control-Allow-Origin "*"`

It will be nice to only configure that for `/api/event` I think, but it is okay to start from there and then you can customize on case by case bass

Your configuration should look like this 
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Protocols h2 http/1.1
        ServerName analytics.shikkanime.fr
        Header always set Access-Control-Allow-Origin "*"

        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://192.168.1.200:9001/
        ProxyPassReverse / http://192.168.1.200:9001/

SSLCertificateFile /etc/letsencrypt/live/analytics.shikkanime.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/analytics.shikkanime.fr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by gernest** [comment]
I'm very happy that you are trying my software.

**Comment by Ziedelth** [comment]
![image](https://github.com/vinceanalytics/vince/assets/45169338/5cf81f86-7091-4d67-a13f-b376ce36410d)
![image](https://github.com/vinceanalytics/vince/assets/45169338/13e315b2-8abc-419e-bc56-0b33fadf9130)

I've got another problem (on different computer and another browser, I can not test for the moment on the previous device).
Brace & Ublock, only ublock seems to block the request

**Comment by gernest** [comment]
So, I have a suggestion that will solve this problem for now.

- leave `analytics.shikkanime.fr` apache config as is
- Update `shikkanime.fr` apache config  add `/api/event` but proxy pass it to `https://analytics.shikkanime.fr`
```
  <Location /api/event>
    ProxyPass https://analytics.shikkanime.fr/api/event
    ProxyPassReverse https://analytics.shikkanime.fr/api/event
  </Location>
```
-  Update the vince script  to have `data-api="https://shikkanime.fr/api/event"`


This will make sure you serve the events api on the domain.

In the future we should do better in documenting and  reduce pain  around `cors` stuff.

**Comment by Ziedelth** [comment]
Hmmm... Now I have a different issue, but it's seem to come from my backend or my secure headers...
```html
<script data-domain="shikkanime.fr" data-api="https://shikkanime.fr/api/event">
                (function(){"use strict";var n,s,i,r,d,t=window.location,e=window.document,c=e.currentScript,h=c.getAttribute("data-api")||u(c);function l(e){console.warn("Ignoring Event: "+e)}function u(e){return new URL(e.src).origin+"/api/event"}function a(n,s){if(/^localhost$|^127(\.[0-9]+){0,2}\.[0-9]+$|^\[::1?\]$/.test(t.hostname)||t.protocol==="file:")return l("localhost");if(window._phantom||window.__nightmare||window.navigator.webdriver||window.Cypress)return;try{if(window.localStorage.vince_ignore==="true")return l("localStorage flag")}catch{}var i,o={};o.n=n,o.u=t.href,o.d=c.getAttribute("data-domain"),o.r=e.referrer||null,o.w=window.innerWidth,s&&s.meta&&(o.m=JSON.stringify(s.meta)),s&&s.props&&(o.p=s.props),i=new XMLHttpRequest,i.open("POST",h,!0),i.setRequestHeader("Content-Type","text/plain"),i.send(JSON.stringify(o)),i.onreadystatechange=function(){i.readyState===4&&s&&s.callback&&s.callback()}}r=window.vince&&window.vince.q||[],window.vince=a;for(n=0;n<r.length;n++)a.apply(this,r[n]);function o(){if(i===t.pathname)return;i=t.pathname,a("pageview")}s=window.history,s.pushState&&(d=s.pushState,s.pushState=function(){d.apply(this,arguments),o()},window.addEventListener("popstate",o));function m(){!i&&e.visibilityState==="visible"&&o()}e.visibilityState==="prerender"?e.addEventListener("visibilitychange",m):o()})()
            </script>
```

![image](https://github.com/vinceanalytics/vince/assets/45169338/021cc99c-f0c3-4121-ab0e-80418a840acd)
![image](https://github.com/vinceanalytics/vince/assets/45169338/ccd889a8-1e5d-42f7-80f1-d739d37f58fa)

Main Apache redirection (shikkanime.fr):
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Protocols h2 http/1.1
        Header always set Access-Control-Allow-Origin "*"
        ServerName shikkanime.fr
        Redirect permanent / https://www.shikkanime.fr/

        <Location /api/event>
                ProxyPass https://analytics.shikkanime.fr/api/event
                ProxyPassReverse https://analytics.shikkanime.fr/api/event
        </Location>

SSLCertificateFile /etc/letsencrypt/live/shikkanime.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/shikkanime.fr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Analytics Apache:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Protocols h2 http/1.1
        ServerName analytics.shikkanime.fr
        Header always set Access-Control-Allow-Origin "*"

        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://192.168.1.200:9001/
        ProxyPassReverse / http://192.168.1.200:9001/

SSLCertificateFile /etc/letsencrypt/live/analytics.shikkanime.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/analytics.shikkanime.fr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by gernest** [comment]
I see, we are making progress. Now we gotta fix that, basically we need to return the  origin instead of `*`.  Let me check how to do it in apache.

**Comment by gernest** [comment]
So, lets update and specify the origin. 

Change this
```
        Header always set Access-Control-Allow-Origin "*"
```

To

```
        Header always set Access-Control-Allow-Origin "https://www.shikkanime.fr"
```

Lets see if the browser will be happy. We will cleanup our configurations after we get this to work first.

**Comment by Ziedelth** [comment]
Now it's seemed blocked by my API, since it's also registered as /api on shikkanime.fr/api
![image](https://github.com/vinceanalytics/vince/assets/45169338/0c1eaf65-e5eb-45b2-bada-de83d8dc263f)

**Comment by gernest** [comment]
Mmh! It says 404 not blocked.

**Comment by gernest** [comment]
Oh! Right, I see your point.

**Comment by gernest** [comment]
Where do you configure your `api`?

**Comment by Ziedelth** [comment]
At /api

For example: `https://www.shikkanime.fr/api/v1/episodes`

**Comment by gernest** [comment]
I meant in the apache config  we can register `/api/event` earlier than `/api` to take precendence.

**Comment by Ziedelth** [comment]
My API is not registered in my Apache configs, it's directly my container that listens on this route (Ktor Server). So I think there's no priority rule and Ktor takes priority... That's why I was saying that I think it's coming from my side for the 404 error

**Comment by gernest** [comment]
It is late here,  I'm going to sleep. Will check out later tomorrow.

This is more a server configuration issue and less of a vince bug, still we need to resolve it and understand how to safely deploy the api.

For now, just reset to configuration from the beginning and we can solve sending events directly to `analytics.shikkanime.fr`

have  good day or night!

**Comment by gernest** [comment]
Hi @Ziedelth ,

So, for cors on `/api/event` endpoint here are the headers we set

```
	w.Header().Set("Access-Control-Allow-Origin", r.Header.Get("Origin"))
	w.Header().Set("Access-Control-Allow-Methods", http.MethodPost)
	w.Header().Add("Access-Control-Allow-Headers", "Content-Type")
```

For some reason apache strips them  down or something ?

We can manually set them in the analytics config

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        Protocols h2 http/1.1
        ServerName analytics.shikkanime.fr
        Header always set Access-Control-Allow-Origin "https://www.shikkanime.fr
        Header always set Access-Control-Allow-Methods "POST"
        Header always set Access-Control-Allow-Headers "Content-Type"

        ProxyPreserveHost On
        ProxyRequests On
        ProxyPass / http://192.168.1.200:9001/
        ProxyPassReverse / http://192.168.1.200:9001/

SSLCertificateFile /etc/letsencrypt/live/analytics.shikkanime.fr/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/analytics.shikkanime.fr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

The rest, including the script should remain like it was at the beginning of this issue.

**Comment by Ziedelth** [comment]
Well, I changed all the settings to be back to the beginning of the issue and I modify the Apache configuration like you said. But I think Ublock detect an analytic script...
![image](https://github.com/vinceanalytics/vince/assets/45169338/55bc2b72-750f-45d1-b21f-6763a61a3c1f)

**Comment by gernest** [comment]
Do you see any error message or reason  for blocking the script?

**Comment by gernest** [comment]
So, we need to confirm if CORS is still the issue or not.

**Comment by Ziedelth** [comment]
I managed to open Ublock's debug console to see why it was blocking the request. 
I see that there's the following regex that seems to match my domain name, I'll try changing the prefix to see if that solves the problem.

I'll get back to you after investigating.

![image](https://github.com/vinceanalytics/vince/assets/45169338/7a30bc57-9416-41b0-accf-1eac12ba563e)
![image](https://github.com/vinceanalytics/vince/assets/45169338/136d3a99-0264-45bd-9188-36aa340233b8)

**Comment by Ziedelth** [comment]
Yeah, right. There was a regex that blocks every prefix with "analytics". By renaming it "vince.shikkanime.fr", I don't have to worry anymore. 

Sorry for the inconvenience

**Comment by gernest** [comment]
> Sorry for the inconvenience

No worries, I'm happy to help.
