### ISSUE TITLE
Getting validation error while starting vince server

### ISSUE THREAD

**Issue by ankitsridhar16** [vinceanalytics/vince#7]
I am following the steps mentioned at - https://www.vinceanalytics.com/
I downloaded and installed via curl and then using the command - `vince --data=vince-data --domains=example.com` to start the server. 
I am getting the following error:
`{"time":"2024-04-04T18:57:46.114255+05:30","level":"ERROR","msg":"Exited process","err":"validation error:\n - node.id: value is required [required]"}`

**Comment by ankitsridhar16** [comment]
So I looked at the closed issues while starting locally we need to add this additional flag `--nodeId=1` . I think we can add this it to the docs repo - https://github.com/vinceanalytics/vinceanalytics.github.io/blob/master/sources/1-getting-started.md

**Comment by ankitsridhar16** [comment]
Sure I will file a PR

**Comment by ankitsridhar16** [comment]
@gernest I have filed a PR - https://github.com/vinceanalytics/vinceanalytics.github.io/pull/1

**Comment by ankitsridhar16** [comment]
@gernest I am trying to run and test locally . Started the server with - `vince --data=vince-data --domains=vinceanalytics.com --authToken=xxxx --nodeId=1` but when trying to curl I get 
```
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Methods: OPTIONS, GET, POST
X-Vince-Version: v0.0.67
Date: Thu, 04 Apr 2024 15:47:14 GMT

```

**Comment by gernest** [comment]
show me the curl command

**Comment by ankitsridhar16** [comment]
`curl -o - -I http://localhost:8080/api/v1/version      `

**Comment by gernest** [comment]
You are missing auth token header `-H "Authorization: Bearer ${TOKEN}" ` replace `${TOKEN}` with the value you set on `--authToken=xxxx` flag.

**Comment by gernest** [comment]
See https://github.com/vinceanalytics/vince/issues/1#issuecomment-1991699320 for details

**Comment by ankitsridhar16** [comment]
`curl -o - -I http://localhost:8080/api/v1/version -H "Authorization: Bearer myauth"  ` this is what you are referring to if my start command is `vince --data=vince-data --domains=vinceanalytics.com --authToken=myauth --nodeId=1` ?

**Comment by gernest** [comment]
> `curl -o - -I http://localhost:8080/api/v1/version -H "Authorization: Bearer myauth" ` this is what you are referring to if my start command is `vince --data=vince-data --domains=vinceanalytics.com --authToken=myauth --nodeId=1` ?

correct.

**Comment by ankitsridhar16** [comment]
> > `curl -o - -I http://localhost:8080/api/v1/version -H "Authorization: Bearer myauth" ` this is what you are referring to if my start command is `vince --data=vince-data --domains=vinceanalytics.com --authToken=myauth --nodeId=1` ?
> 
> correct.

I am still getting a 401

**Comment by gernest** [comment]
> > > `curl -o - -I http://localhost:8080/api/v1/version -H "Authorization: Bearer myauth" ` this is what you are referring to if my start command is `vince --data=vince-data --domains=vinceanalytics.com --authToken=myauth --nodeId=1` ?
> > 
> > 
> > correct.
> 
> I am still getting a 401

can you share  the curl with `-v` flag output please.

**Comment by ankitsridhar16** [comment]
```
curl -o - -I http://localhost:8080/api/v1/version -H "Authorization: Bearer myauth" -v                                                   ──(Thu,Apr04)─┘
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> HEAD /api/v1/version HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.84.0
> Accept: */*
> Authorization: Bearer myauth
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
HTTP/1.1 401 Unauthorized
< Access-Control-Allow-Credentials: true
Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Headers: Content-Type, Authorization
< Access-Control-Allow-Methods: OPTIONS, GET, POST
Access-Control-Allow-Methods: OPTIONS, GET, POST
< X-Vince-Version: v0.0.67
X-Vince-Version: v0.0.67
< Date: Thu, 04 Apr 2024 16:35:07 GMT
Date: Thu, 04 Apr 2024 16:35:07 GMT

```

**Comment by gernest** [comment]
@ankitsridhar16 so, the `/version` endpoint used to be there to check if installation was ok. But I removed it after making vince distributed.

At the moment this is expected as we know vince is running.

Try something that is expected like getting current visitors.

```
curl  "http://localhost:8080/api/v1/stats/realtime/visitors?site_id=vinceanalytics.com" \
  -H "Authorization: Bearer myauth"
```

We could do better and use something that actually works in documentation. The `/version` endpoint   example should be removed from docs.

**Comment by ankitsridhar16** [comment]
@gernest that works. Should I file another PR to update the docs ?

**Comment by gernest** [comment]
> @gernest that works. Should I file another PR to update the docs ?

yes, please.

**Comment by ankitsridhar16** [comment]
> > @gernest that works. Should I file another PR to update the docs ?
> 
> yes, please.

So I think having the `/version` api is good. Also if I update the command using the previous URL it doesn't return any kind of response, it will just return a status code. @gernest what would be a good implementation ?

**Comment by gernest** [comment]
You can return actual version. Vince has a version package with the version value https://github.com/vinceanalytics/vince/blob/main/version/version.go

**Comment by ankitsridhar16** [comment]
So we keep the `/version` and add the code to support the api. Okay I will work on this and update the code.

**Comment by gernest** [comment]
> @gernest imo the version endpoint doesn't necessarily be behind auth check

@ankitsridhar16 

You are right. I wasn't very clear earlier. So what I want you to do is 

- expose `/version` endpoint just like we already do with `/metrics`
- I'm fine either returning the semver string or structured json
- no auth is needed ( see what `/metrics` ) does for inspiration

Note that we will be using `/version` and not `/api/v1/version`.

What do you think?

**Comment by ankitsridhar16** [comment]
> > @gernest imo the version endpoint doesn't necessarily be behind auth check
> 
> @ankitsridhar16
> 
> You are right. I wasn't very clear earlier. So what I want you to do is
> 
> * expose `/version` endpoint just like we already do with `/metrics`
> * I'm fine either returning the semver string or structured json
> * no auth is needed ( see what `/metrics` ) does for inspiration
> 
> Note that we will be using `/version` and not `/api/v1/version`.
> 
> What do you think?

yes this works

**Comment by ankitsridhar16** [comment]
@gernest I have created a PR - https://github.com/vinceanalytics/vince/pull/8. Let me know if there are any required changes.
I have filed another PR for updating the docs - https://github.com/vinceanalytics/vinceanalytics.github.io/pull/2

**Comment by ankitsridhar16** [comment]
@gernest I think we can close this issue
